//
//  MainFeedModels.swift
//  Shudder
//
//  Created by Zain N. on 10/23/18.
//  Copyright (c) 2018 Mapfit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainFeed
{
  // MARK: Use cases
  
  enum Data
  {
    struct Request
    {
        var searchString: String
        
    }
    struct Response
    {
        var images: [UIImage]?
        var responseCode: Int
        
    }
    struct ViewModel
    {
        var images: [UIImage]?
        var responseCode: Int
    }
  }
}
