//
//  MainFeedPresenter.swift
//  Shudder
//
//  Created by Zain N. on 10/23/18.
//  Copyright (c) 2018 Mapfit. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainFeedPresentationLogic
{
  func presentVideos(response: MainFeed.Data.Response)
}

class MainFeedPresenter: MainFeedPresentationLogic
{
    
  weak var viewController: MainFeedDisplayLogic?
  
  // MARK: Do something
  
  func presentVideos(response: MainFeed.Data.Response)
  {
    
    switch response.responseCode {
    case 200:
        let viewModel = MainFeed.Data.ViewModel(images: response.images, responseCode: 200)
        viewController?.displayVideos(viewModel: viewModel)
    case 300:
        let viewModel = MainFeed.Data.ViewModel(images: nil, responseCode: 300)
        viewController?.displayVideos(viewModel: viewModel)
    default:
        let viewModel = MainFeed.Data.ViewModel(images: response.images, responseCode: 400)
        viewController?.displayVideos(viewModel: viewModel)
    }
    

  }
}
